export const ACTIONS = {
    SET_IS_LOGGED: "SET_IS_LOGGED",
    SET_USER_NAME: "SET_USER_NAME",
    SET_USER_DAYS_LIST: "SET_USER_DAYS_LIST",
    SET_USER_WEEKS_LIST: "SET_USER_WEEKS_LIST",
    SET_IS_DARK_MODE: "SET_IS_DARK_MODE"
};